#Mongo Express Deployment Document
apiVersion: apps/v1
kind: Deployment #Component Type
metadata:
  name: mongoexpress-deployment #Deployment Name
  labels: #Deployment Label
    app: mongoexpress
spec: #Deployment Specifications
  replicas: 1 # Number of Replicas
  selector:
    matchLabels: #It'll connect the Deployment to the Pod according to the "labels" value
      app: mongoexpress
  template: #Blueprint for the Pod
    metadata:
      labels: #Pod Label
        app: mongoexpress
    spec: #Pod Specifications
      containers:
      - name: mongoexpress
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret #Must match with the Secret "name" that is storing our MongoDB "username" and "password" environment variables
              key: mongo-root-username #key in Secret YAML
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret #Must match with the Secret "name" that is storing our MongoDB "username" and "password" environment variables
              key: mongo-root-password #key in Secret YAML
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap #Must match with the ConfigMap "name" that is storing our MongoDB "server" environment variable
              key: database-url #key in ConfigMap YAML