#MongoDB Deployment Document
apiVersion: apps/v1
kind: Deployment #Component Type
metadata:
  name: mongodb-deployment #Deployment Name
  labels: #Deployment Label
    app: mongodb
spec: #Deployment Specifications
  replicas: 1 # Number of Replicas
  selector:
    matchLabels: #It'll connect the Deployment to the Pod according to the "labels" value
      app: mongodb
  template: #Blueprint for the Pod
    metadata:
      labels: #Pod Label
        app: mongodb
    spec: #Pod Specifications
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017 #Must match with Service "targetPort". It connects the Pods to the Service
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret #Must match with the Secret "name" that is storing our MongoDB "username" and "password" environment variables
              key: mongo-root-username #key in Secret YAML
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret #Must match with the Secret "name" that is storing our MongoDB "username" and "password" environment variables
              key: mongo-root-password #key in Secret YAML
--- 
#In YAML, the abouve line indicates that a new document will be written below
#MongoDB Service Document
apiVersion: v1
kind: Service #Component Type
metadata:
  name: mongodb-service #Service Name
spec: #Service Specifications
  selector:
    app: mongodb #Must match with Pod "label". It connects the Service to the Pod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 #Must match with Pod "containerPort". It connects the Service to the Pods