#Mosquitto (Message Broker that implements MQTT) Deployment Document
apiVersion: apps/v1
kind: Deployment #Component Type
metadata:
  name: mosquitto-deployment #Deployment Name
  labels: #Deployment Label
    app: mosquitto
spec: #Deployment Specifications
  replicas: 1 #Number of Replicas
  selector:
    matchLabels: #It'll connect the Deployment to the Pod according to the "labels" value
      app: mosquitto
  template: #Blueprint for the Pod
    metadata:
      labels: #Pod Label
        app: mosquitto
    spec: #Pod Specifications
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:1.6.2
          ports:
            - containerPort: 1883 #Must match with Service "targetPort". It connects the Pods to the Service