apiVersion: v1
kind: Secret #Component Type
metadata:
  name: docker-secret #Secret Name
type: Opaque #Secret Type (Opaque is the default used for key-value pairs)
data: #Where the data will be
  .dockerconfigjson: <YourBase64EncondedFileContentHere> #It will contain the base64 encoded of the .docker/config.json file
type: kubernetes.io/dockerconfigjson #Node Type

# Command line to create the above secret from the CLI
## kubectl create secret generic docker-secret --from-file=.dockerconfigjson=.docker/config.json --type=kubernetes.io/dockerconfigjson

# This creates a Secret in two steps (common used when you have more than one Private Docker Registry):
## #1st: docker login
## #2nd: create the Secret from the .docker/config.json file

###

# This creates a Secret in one step (common used when you have just one Private Docker Registry):
## Login and create the secret in the same command
## kubectl create secret docker-registry docker-secret --docker-server=<PrivateDockerRegistryUrl> --docker-username=<PrivateDockerRegistryUsername> --docker-password=<PrivateDockerRegistryPassword>